#include "gl_loader.h"

#include <GL/gl.h>

#include "gl_export_aliases.inl"

#define GLREMIX_GL_VOID_WRAPPER(name, params, args)                                                        \
    extern "C" __declspec(dllexport) void APIENTRY name params                                             \
    {                                                                                                      \
        using FnType = void(APIENTRY*) params;                                                             \
        if (auto override_fn = reinterpret_cast<FnType>(glremix::gl::find_override(#name)))                \
        {                                                                                                  \
            override_fn args;                                                                              \
            return;                                                                                        \
        }                                                                                                  \
        glremix::gl::report_missing_function(#name);                                                       \
    }

#define GLREMIX_GL_RETURN_WRAPPER(ret, name, params, args)                                                 \
    extern "C" __declspec(dllexport) ret APIENTRY name params                                              \
    {                                                                                                      \
        using FnType = ret(APIENTRY*) params;                                                              \
        if (auto override_fn = reinterpret_cast<FnType>(glremix::gl::find_override(#name)))                \
        {                                                                                                  \
            return override_fn args;                                                                       \
        }                                                                                                  \
        glremix::gl::report_missing_function(#name);                                                       \
        return {};                                                                                         \
    }

#include "gl_wrappers.inl"

#undef GLREMIX_GL_VOID_WRAPPER
#undef GLREMIX_GL_RETURN_WRAPPER

namespace glremix::gl
{
    // Store mapping of function names to function pointers based off autogenerated .inl file (not in this project)
	// CMakeLists.txt generates the file in external/shim-platform/generated using a Python script
	void register_core_wrappers()
	{
	#include "gl_register.inl"
	}
}
